from py2app.build_app import py2app as _py2app
from setuptools import setup


class PatchedPy2App(_py2app):
    """Clear setuptools metadata that py2app 0.28 rejects."""

    def finalize_options(self):
        self.distribution.install_requires = []
        super().finalize_options()

APP = ["icloudphotonator/__main__.py"]
DATA_FILES = []
OPTIONS = {
    "argv_emulation": False,
    "iconfile": None,
    "plist": {
        "CFBundleName": "iCloudPhotonator",
        "CFBundleDisplayName": "iCloudPhotonator",
        "CFBundleIdentifier": "com.hanselstner.icloudphotonator",
        "CFBundleVersion": "0.1.0",
        "CFBundleShortVersionString": "0.1.0",
        "LSMinimumSystemVersion": "13.0",
        "NSHighResolutionCapable": True,
        "CFBundleDocumentTypes": [],
    },
    "packages": [
        "icloudphotonator",
        "icloudphotonator.ui",
        "customtkinter",
        "osxphotos",
        "bitarray",
        "bitmath",
        "bitstring",
        "bpylist2",
        "bs4",
        "charset_normalizer",
        "cgmetadata",
        "click",
        "CoreAudio",
        "AVFAudio",
        "AVFoundation",
        "AppKit",
        "AppleScriptKit",
        "AppleScriptObjC",
        "Cocoa",
        "Contacts",
        "CoreFoundation",
        "CoreLocation",
        "CoreMedia",
        "CoreML",
        "CoreServices",
        "FSEvents",
        "Foundation",
        "jedi",
        "mac_alias",
        "mako",
        "makelive",
        "Metal",
        "more_itertools",
        "objc",
        "objexplore",
        "osxmetadata",
        "packaging",
        "parso",
        "pathvalidate",
        "Photos",
        "photoscript",
        "pydantic",
        "pydantic_core",
        "psutil",
        "ptpython",
        "prompt_toolkit",
        "pygments",
        "Quartz",
        "requests",
        "rich",
        "rich_theme_manager",
        "shortuuid",
        "ScriptingBridge",
        "strpdatetime",
        "tenacity",
        "textx",
        "toml",
        "tzdata",
        "utitools",
        "Vision",
        "whenever",
        "wrapt",
        "xattr",
        "xdg_base_dirs",
        "yaml",
    ],
    "includes": [
        "sqlite3",
        "tkinter",
        "81d243bd2c585b0f4821__mypyc",
        "_cffi_backend",
        "objc",
        "Foundation",
        "AppKit",
        "markdown2",
        "pytimeparse2",
        "wurlitzer",
    ],
    "excludes": ["pytest", "pytest_asyncio"],
}

setup(
    app=APP,
    data_files=DATA_FILES,
    cmdclass={"py2app": PatchedPy2App},
    options={"py2app": OPTIONS},
    setup_requires=["py2app"],
)
